name: hyper_ui
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <=4.0.0'
dependencies:
  badges: ^3.1.1
  blur: ^3.1.0
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  custom_clippers: ^2.0.0
  dio: ^5.0.1
  dotted_border: ^2.0.0+3
  faker_dart: ^0.2.1
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.3
  flutter_image_compress: ^2.0.3
  flutter_inappwebview: ^5.7.2+3
  flutter_map: ^5.0.0
  flutter_markdown: ^0.6.12
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.4.1
  geolocator: ^10.0.1
  get_it: ^7.6.4
  google_fonts: ^5.1.0
  http: ^1.1.2
  image_picker: ^1.0.4
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.0.11
  permission_handler: ^10.0.2
  qr_flutter: ^4.0.0
  syncfusion_flutter_charts: ^22.2.12
  url_launcher: ^6.1.6
  uuid: ^4.0.0
dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/icon/
